@baseUrl = http://127.0.0.1:8000/api
@token = 49f6f23a977ef87cce994151574402cd8912f51e

### 1. Signup — cadastrar novo usuário
POST {{baseUrl}}/signup/
Content-Type: application/json

{
    "username": "joaosilva",
    "email": "joaosilva@email.com",
    "password": "joaosilva",
    "tipo": "CLIENTE",
    "cpf": "89786756454",
    "telefone": "(84) 934550716"
}


### 2. Login — autenticar e obter token
POST {{baseUrl}}/login/
Content-Type: application/json

{
    "username": "placidoneto",
    "password": "placidoneto"
}

### 2.1 Login — autenticar e obter token
POST {{baseUrl}}/login/
Content-Type: application/json

{
    "username": "joaosilva",
    "password": "joaosilva"
}

### 3. Perfil — dados do usuário autenticado (requer token)
GET {{baseUrl}}/perfil/
Authorization: Token {{token}}


### Registrar um vendedor COM perfil de vendedor
POST {{baseUrl}}/registro/
Content-Type: application/json

{
    "username": "loja_tech",
    "email": "contato@lojatech.com",
    "password": "senha123",
    "tipo": "VENDEDOR",
    "telefone": "84999990000",
    "vendedor": {
        "nome_loja": "Loja Tech RN",
        "cpf_cnpj": "12345678000199",
        "avaliacao": "4.5"
    }
}

### Registrar um cliente COM perfil de cliente
POST {{baseUrl}}/registro/
Content-Type: application/json

{
    "username": "maria_cliente",
    "email": "vamossla@email.com",
    "password": "senha123",
    "tipo": "CLIENTE",
    "telefone": "84999990001",
    "cliente": {
        "cpf": "12345432237",
        "endereco_entrega": "Av. Salgado Filho, 1000 - Natal/RN"
    }
}

### Logar com perfil de vendedor
POST {{baseUrl}}/login_usuario/
Content-Type: application/json

{
    "username": "loja_tech",
    "password": "senha123"
}

### Logar com perfil de cliente
POST {{baseUrl}}/login_usuario/
Content-Type: application/json

{
    "username": "maria_cliente",
    "password": "senha123"
}

### Verificar Perfil perfil_usuario
GET {{baseUrl}}/perfil_usuario/
Authorization: Token {{token}}