# Generated by Django 6.0.4 on 2026-04-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'formas_pagamento',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cliente')),
            ],
            options={
                'db_table': 'enderecos',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('qtd_estoque', models.IntegerField(default=0)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.categoria')),
            ],
            options={
                'db_table': 'itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cliente')),
                ('endereco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.endereco')),
                ('forma_pagamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.formapagamento')),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pedido')),
            ],
            options={
                'db_table': 'itens_pedido',
                'ordering': ['pedido_id'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.endereco')),
            ],
            options={
                'db_table': 'vendedores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='vendedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.vendedor'),
        ),
    ]
