# Generated by Django 6.0.4 on 2026-04-22 18:18

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categoria_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='qtd_estoque',
            new_name='estoque',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vendedor_id',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='endereco_id',
        ),
        migrations.AddField(
            model_name='item',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('roupas', 'Roupas e Acessórios'), ('livros', 'Livros'), ('alimentos', 'Alimentos'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cpf_cnpj',
            field=models.CharField(default=None, max_length=18, unique=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='item',
            table='produtos',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
