# Generated by Django 6.0.4 on 2026-04-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_categoria_formapagamento_endereco_item_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['estado']},
        ),
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'ordering': ['tipo']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'ordering': ['pedido_id']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='endereco',
            table='enderecos',
        ),
        migrations.AlterModelTable(
            name='formapagamento',
            table='formas_pagamento',
        ),
        migrations.AlterModelTable(
            name='item',
            table='itens',
        ),
        migrations.AlterModelTable(
            name='itempedido',
            table='itens_pedido',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
        migrations.AlterModelTable(
            name='vendedor',
            table='vendedores',
        ),
    ]
